os: linux
language: minimal
dist: trusty
sudo: required
services: docker
install: skip
addons:
  apt:
    packages:
    - docker-ce
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: C6GGuFAptgzQLTfRVbheCPGh0S1ZHFA+GKKcqMPOik5t3CY9xqZUsHOm55sptI4FfKmSgzM/C9LMaL08zCeyn9H80Sjhv5zMTp2s1i3FFHCmmwMSPaZs7uwMuB2kIVFTaSQQGihZklKzbLJOGIrJJC5s4es1JHii8Tc0cjp9ck6tlb+kQ2rk1pXtVUo0E5hXFM0zMT6KX+YmtAYvC8yTSEuZLsISkSZlZa0Wa/0NX3vvn2xTP6Wyk9FIjtN4Pob3rRjee80wADVc0Pn2nlKa6zZnU1+/IqQN7bPN0pfpUBhMmaSLUYDbHhoDChEQnFxo0vKupbTSS30iOkZMU7HAnDKdxgQSg8jJ4fDLOPK8jIDRODXHcORqeXsI92CUX8ldCezvy24A8x0bUlluswBYGPxILzqPkpPTaDpvw7h56/RTyjX3ia3X3aIvCDnZhmFvR5HFjjPoY78e0MXtf7N3npSmf/PJD7G80IUtkCfYI+Ms06HFT6tTjMXAGSKLSNVFgnxZeoLAerOAYPJwPqkdawNxiIFWbVa+OS52TUGrSPXvJipKHjgbHpBx/cgFQz5FOUm1SGkIEaz9HkE+QrwOnb0hvWcXRB9ugq3nqmYYowwceuTAIWX8wsoAWy0U7VtZKFYetMoxwuyL377m+cwovLdXU/5hF147H2aX7n/jGuA=
  file_glob: true
  file: release/*.tgz
  on:
    repo: 1138-4EB/hwd-ide
    branch: master
    tags: true
stages:
- build images
- test
jobs:
  include:
    - script: "./travis/travis.sh"
    - stage: build images
      script: "./filebrowser/images.sh"
      deploy:
      - provider: script
        skip_cleanup: true
        script: "./filebrowser/deploy2dockerhub.sh"
        on:
          repo: 1138-4EB/hwd-ide
          branch: develop

env:
  global:
    - secure: "wwbV8qTdQa94rbCZCrBt2r5ngaNEUgr2zsiyLCLREzsrGN0SbxKZCYbBWReVUbdK3vaylPl7x5rNvl/trkROyUhVlNnHdvtX8ALc6jtUHr0EdVygSVNZfq1eVIHKn0heVI1OsRR98KJl2HkTas/6jWjk8WgO4mZqvC2Pp99aFLc34xvwxPJX7sAtGLgprpt1ULKAJz7V3ONwqAvu94oJpE2R+XCcPjcIxWIEKCfy0Xm/F59Ne8DG+KqCrNRI5d/hV9nent0RjDWl/BuQ+5rMp4qyiPd30HGRN5XXq8oFW3k6DM6OSn9cgyUdQ6PQ6GbYplaLyMltBQZaqW9jcXPtwhpOkIuIlkPWDGgz8Yd3S/67drR/dPymz4CVSBBDfZRguF+8piVQT0ZSnOBQSwDfwHOgjMY2NCQrgeIBOaaW1CYmwwyMPVKQ3MBRjX46XkVJrgDUnlbLzJ/R/gG55FeQvZu1lrNwUxZer7RG1TtlLSLhQ8WPJcHIeF110YxqaIawfFWzF5T5iimHclWa4Ld8HV9/z/TuY1ufbj6vcCnzSjcFOhPmyeJ7nLiKQ4nFzE0VLt5zHpnaW0ac+gmXfQse46uNr/F9mLZY+taXOy9gNp8rMg0aADXyagPDrebcwn5TyMAD9Q2mTeoy+xHXb2MOHdNnNvhTGRdqYT98ESr8vk4=" #U
    - secure: "rEiTEX24Zi9FwQwrj4irPZrevczN+oSSlWZQYEcIGalOXarCrUvDF8kPm/vdfvJMo39VBlIQjdBKRcefDi0cRg/x6XGz4ox21WCeSA1TJWKc+xllwNuYXVxiKmvxfhWlMtRpUdVZVYzH8LgTnVLBWSFc7r8fOeFw2FqBs63ayMrr4BUMe01a6pDtM7QW6JIi2oJ2qIwwTx/kMyQX2Cr5bW4R22+pNG2ThRgjwzUi2CFqOW0Nq4kruyPbGjVQilshsRQF81jFmlTfWX7eJLyC9CWnBGnwY7nbH/Jv1IVhny/B+cptXZ/XrzjmFbB3C548T6wLUivfbBcKwgVjel+yb9oj/+5fhdjngDKpi09gX//hd230iCMqwBlesdVVqhu2Ld+qmqX1fG0DejxqnUHR67+PMA1/yAIKTt6m4ykhrdCwme5Y2dYXMpDjhdwXz5VkIGy7NhGu5rp9k8uAU14D6m4MedntaexbawnQ+pLsR1E82Tvt+PdF5NPd7lm1XnhiWKkoHFRlgfZ4dSRJCjH2Qs5kEVqer48GXrdcf97WaWBvlydTPtL8vSDRriXknGCj3r4SbpV9ul3EYoytUWWEStisgNgeG8s+Q0w00I+CYk1kcgkF8AAB1UNT0YQDxTzRAUhG7JbZH4xJKdTIiTQuLHMzHFrtRi8M/XjW8iSmYdg=" #P
