branches:
  except:
    - appveyor

os: linux
language: minimal
dist: trusty
sudo: required
services: docker
install: skip

addons:
  apt:
    packages:
      - docker-ce

script:
   - . ./travis/travis.sh

deploy:
#  overwrite: false
  provider: releases
  skip_cleanup: true
  api_key:
    secure: C6GGuFAptgzQLTfRVbheCPGh0S1ZHFA+GKKcqMPOik5t3CY9xqZUsHOm55sptI4FfKmSgzM/C9LMaL08zCeyn9H80Sjhv5zMTp2s1i3FFHCmmwMSPaZs7uwMuB2kIVFTaSQQGihZklKzbLJOGIrJJC5s4es1JHii8Tc0cjp9ck6tlb+kQ2rk1pXtVUo0E5hXFM0zMT6KX+YmtAYvC8yTSEuZLsISkSZlZa0Wa/0NX3vvn2xTP6Wyk9FIjtN4Pob3rRjee80wADVc0Pn2nlKa6zZnU1+/IqQN7bPN0pfpUBhMmaSLUYDbHhoDChEQnFxo0vKupbTSS30iOkZMU7HAnDKdxgQSg8jJ4fDLOPK8jIDRODXHcORqeXsI92CUX8ldCezvy24A8x0bUlluswBYGPxILzqPkpPTaDpvw7h56/RTyjX3ia3X3aIvCDnZhmFvR5HFjjPoY78e0MXtf7N3npSmf/PJD7G80IUtkCfYI+Ms06HFT6tTjMXAGSKLSNVFgnxZeoLAerOAYPJwPqkdawNxiIFWbVa+OS52TUGrSPXvJipKHjgbHpBx/cgFQz5FOUm1SGkIEaz9HkE+QrwOnb0hvWcXRB9ugq3nqmYYowwceuTAIWX8wsoAWy0U7VtZKFYetMoxwuyL377m+cwovLdXU/5hF147H2aX7n/jGuA=
  file_glob: true
  file: "release/*.tar.gz"
  on:
    repo: 1138-4EB/elide
    branch: stable
#    all_branches: true
    tags: true
