# DEFAULTS:
#   database  ./filebrowser.db
#   noauth    false
#   username  admin
#   password
#   address   127.0.0.1
#   log       stdout
#   port      8080
#   cert
#   key
#   root      .
#   baseurl

database: /var/lib/filebrowser/filebrowser.db
noauth: false
username: hwd
address: ""
log: stdout
port: 8080
root: /srv

# DEPRECATED?
#   commands:
#     - "*"
#     - cp$
#     - ghdl$
#     - ls$
#     - mv$
#     - python.*
