address: ""
allowCommands: true
allowEdit: true
allowNew: true
commands:
  - ls
  - mv
  - cp
  - ghdl
  - vunit
  - python3
database: /opt/filebrowser/filebrowser.db
log: stdout
noAuth: true
plugin: ""
port: 80
reCaptchaKey: ""
reCaptchaSecret: ""
scope: /srv
