address: ""
allowCommands: true
allowEdit: true
allowNew: true
commands:
  - ls$
  - mv$
  - cp$
  - ghdl$
  - python.*
database: /opt/filebrowser/filebrowser.db
log: stdout
noAuth: true
plugin: ""
port: 8080
reCaptchaKey: ""
reCaptchaSecret: ""
scope: /srv
